CREATE TABLE IF NOT EXISTS schemas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pathogen_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    version INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schema JSONB NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    FOREIGN KEY (pathogen_id) REFERENCES pathogens(id)
);