@folio = http://localhost:8000
# @folio = https://folio-staging.openup.org.za
# @folio = https://folio-ilifu.openup.org.za

@keycloak = http://keycloak.local
# @keycloak = http://localhost:8080
# @keycloak = https://keycloak-staging.openup.org.za
# @keycloak = https://keycloak-ilifu.openup.org.za

# @minio = http://minio.local
# @minio = http://localhost:9000


@realm = agari
@client_id = dms
@client_secret = VDyLEjGR3xDQvoQlrHq5AB6OwbW0Refc

# @username = system.admin@agari.tech
# @username = owner@org1.ac.za
# @username = owner@org2.ac.za
# @username = org-admin@org1.ac.za
# @username = org-admin@org2.ac.za
# @username = test-user1@example.com
# @username = test-user2@example.com
# @username = test-user3@example.com
@username = dirk@openup.org.za

@password = pass123

@testuser1 = a056925c-4d53-417f-a9f6-45e4421654cc

### 1. LOGIN to get access token
# @name login
POST {{keycloak}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}
&grant_type=password
&client_id={{client_id}}
&client_secret={{client_secret}}

###
@token = {{login.response.body.access_token}}

### Keycloak generate magic link
@redirect_uri = https://agari.openup.org.za
# @name magiclink
POST {{keycloak}}/realms/{{realm}}/magic-link
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "test-user2@example.com",
  "client_id": "dms",
  "redirect_uri": "https://agari.openup.org.za",
  "expiration_seconds": 3600,
  "send_email": false
}

### Keycloak authenticate with code
POST {{keycloak}}/realms/agari/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&client_secret={{client_secret}}
&grant_type=authorization_code
&code=[add code here]
&redirect_uri={{redirect_uri}}

##########################
### INFO
##########################

# @name health
GET {{folio}}/info/health

###

# @name databaseHealth
GET {{folio}}/info//health/db

###

# @name whoami
GET {{folio}}/info/whoami
Authorization: Bearer {{token}}

###

# @name permissions
GET {{folio}}/info/permissions
Authorization: Bearer {{token}}

###

# @name userHasResourcePermission

POST {{folio}}/info/permissions/check
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "permission": "create_project",
    "resource_type": "project",
    "resource_id": "80bd4fd2-10e3-4104-abe2-713dfdd92bfa"
}


###

# @name permission_check
POST {{folio}}/info/permissions/check
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "permission": "view_org_private_projects",
    "resource_type": "project",
    "resource_id": "80bd4fd2-10e3-4104-abe2-713dfdd92bfa"
}

##########################
### USERS
##########################

# @name get_current_user
GET {{folio}}/info/whoami
Authorization: Bearer {{token}}

###

# @name get_user_by_id
GET {{folio}}/users/{{testuser1}}
Authorization: Bearer {{token}}

###

# @name update_user_by_id
PUT {{folio}}/users/{{testuser1}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "name",
  "surname" : "surname",
  "email": "testuser1@example.com",
  "bio": "lorem",
  "preferences": {
    "theme": "dark"
  },
  "accepted_terms": true,
  "accepted_governance": true
}

###

# @name request_email_change
PUT {{folio}}/users/email
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "redirect_uri": "127.0.0.1",
  "new_email": "test-user2@example.com"
}

###

@inv_token = a1b06b98ea6f9715c81b4be4e0f8956a
# @name confirm_email_change
POST {{folio}}/invites/email//confirm

###

@users_id = e9f23458-7fb1-484a-bf30-82db540c362e
# @name revoke_user_access
DELETE {{folio}}/users/{{users_id}}
Authorization: Bearer {{token}}

###

# @name enable_user_access
POST {{folio}}/users/{{users_id}}
Authorization: Bearer {{token}}


##########################
## ORGANISATIONS
##########################


# @name list_organisations
GET {{folio}}/organisations
Authorization: Bearer {{token}}

###

# @name create_organisation
POST {{folio}}/organisations/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "KNHI",
    "abbreviation": "KNHI",
    "about": "About NKNHI",
    "url": "https://www.knhi.org"
}

###

# @organisation_id = c6bc3b80-01fa-4e96-9b66-64cae90c3acf
@organisation_id = fbec3c00-f914-4f74-baca-34e8335f4bd8

# @name get_organisation
GET {{folio}}/organisations/{{organisation_id}}
Authorization: Bearer {{token}}

###

# @name update_organisation
PUT {{folio}}/organisations/{{organisation_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "about": "Updated Organisation 3"
}

###

# @name delete_organisation
DELETE {{folio}}/organisations/{{organisation_id}}
Authorization: Bearer {{token}}

###

# @name add_organisation_member
POST {{folio}}/organisations/{{organisation_id}}/members
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": "3948dda5-f903-44eb-8d16-759fed3492a1",
    "role": "org-owner"
}

###

# @name organisation_users
GET {{folio}}/organisations/{{organisation_id}}/members
Authorization: Bearer {{token}}

###
# @name remove_organisation_users
DELETE {{folio}}/organisations/members
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": "3948dda5-f903-44eb-8d16-759fed3492a1"
}

##########################
### PATHOGENS
##########################

# @name list_pathogens
GET {{folio}}/pathogens

###

# @name list_pathogens_deleted
GET {{folio}}/pathogens?deleted=true

###

# @name create_pathogen
POST {{folio}}/pathogens
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Malaria Human",
    "description": "Anopheles gambiae",
    "scientific_name": "Anopheles gambiae"
}

###


@pathogen_id = 126fce46-82d2-4ceb-b644-b0ca4de4a40d

# @name get_pathogen
GET {{folio}}/pathogens/{{pathogen_id}}

###

# @name delete_pathogen
DELETE {{folio}}/pathogens/{{pathogen_id}}
Authorization: Bearer {{token}}

###

# @name delete_pathogen_hard
DELETE {{folio}}/pathogens/{{pathogen_id}}?hard=true
Authorization: Bearer {{token}}

###

# @update_pathogen
PUT {{folio}}/pathogens/{{pathogen_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "schema_id": "82b3cb85-4778-45b5-a2e2-97c42e29834e"
}

###

# @name restore_pathogen
POST {{folio}}/pathogens/{{pathogen_id}}/restore
Authorization: Bearer {{token}}

##########################
### SCHEMAS
##########################

# @name list_schemas
GET {{folio}}/schemas
Authorization: Bearer {{token}} 

###

# @name register_schema
POST {{folio}}/schemas/
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary456

------WebKitFormBoundary456
Content-Disposition: form-data; name="metadata"

{
    "pathogen_id": "{{pathogen_id}}",
    "name": "sarscov2",
    "description": "Schema for SARS-CoV-2 pathogen"
}

------WebKitFormBoundary456
Content-Disposition: form-data; name="file"; filename="sars_cov2.json"
Content-Type: application/json

< /home/dimee/Work/OpenUp/SANBI/agari-folio/test/schemas/sars_cov2.json

------WebKitFormBoundary456--



###

@schema_id = 108f50fa-7082-4525-a721-7cdef52d78bf

# @name get_schema
GET {{folio}}/schemas/{{schema_id}}
Authorization: Bearer {{token}} 

###

##########################
### PROJECTS
##########################

# @name list_projects
GET {{folio}}/projects?search=Tim
Authorization: Bearer {{token}}

###

# @name create_project
POST {{folio}}/projects/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cholera Sunday1",
    "description": "",
    "pathogen_id": "{{pathogen_id}}",
    "privacy": "public"
}

###

# @project_id = d4a33900-6fa0-4549-a683-878acfa43f10

### @name get_project
GET {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}

###

# @name update_project
PUT {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "privacy": "public"
}

###

# @name delete_project
DELETE {{folio}}/projects/{{project_id}}
Authorization: Bearer {{token}}

###

# @name delete_project_hard
DELETE {{folio}}/projects/{{project_id}}?hard=true
Authorization: Bearer {{token}}

###

# @name restore_project
POST {{folio}}/projects/{{project_id}}/restore
Authorization: Bearer {{token}}

###

# @name get_activity_log
GET {{folio}}/activity-log/{{project_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "page": 1,
    "limit": 5
}

##########################
### PROJECT USERS
##########################

# @name list_project_users
GET {{folio}}/projects/{{project_id}}/users
Authorization: Bearer {{token}}

###

# @name add_project_users
POST {{folio}}/projects/{{project_id}}/users
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "user_id": "282dd9ee-ad7e-4580-9677-fa37d7ba6435",
    "role": "project-contributor"
}

###

@user_id = 638e2410-c4cf-4854-8258-d600ac289bcc

# @name delete_project_users
DELETE {{folio}}/projects/{{project_id}}/users/{{user_id}}
Authorization: Bearer {{token}}

###

##########################
### SUBMISSIONS2
##########################


@project_id = 03d8f5ac-ab3a-4738-a4f4-bce360d4473a
@submission_id = e4056885-54d4-4dee-affb-96ebc273fff0

### Step 1: Get all submission
# @name getSubmission2
GET {{folio}}/projects/{{project_id}}/submissions2
Authorization: Bearer {{token}}
Content-Type: application/json

###


### Step 1: Create new submission
# @name createSubmission2
POST {{folio}}/projects/{{project_id}}/submissions2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "submission_name": "cholera-sunday3"
}

###

### Step 2: Get the submission details
# @name getSubmission2
GET {{folio}}/projects/{{project_id}}/submissions2/{{submission_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

###


### Step 3a: Upload TSV file 
# @name uploadTSV2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/upload2
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="cholera_1_corrected.tsv"
Content-Type: text/tab-separated-values

< /home/dimee/Work/OpenUp/SANBI/agari-folio/test/data/tsv_files/cholera_1_corrected.tsv

--boundary123--

###

### Step 2b: Upload FASTA file
# @name uploadFASTA2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/upload2
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary456

--boundary456
Content-Disposition: form-data; name="file"; filename="cholera_003.fasta"
Content-Type: text/plain

< /home/dimee/Work/OpenUp/SANBI/agari-folio/test/data/tsv_files/cholera_003.fasta

--boundary456--

###

@file_id = 019bc3f8-7f50-497c-93a2-bb1997004f44

### Step 2c: Delete uploaded file
# @name deleteUploadedFile2
DELETE {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/files2/{{file_id}}
Authorization: Bearer {{token}}

###

### Step 3: Validate submission
# @name validateSubmission2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/validate2
Authorization: Bearer {{token}}
Content-Type: application/json

###

### Step 3b: Validate submission
# @name ViewValidation
GET {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/validate2
Authorization: Bearer {{token}}

###


### Step 4: Finalise submission
# @name finalizeSubmission2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/finalise
Authorization: Bearer {{token}}

###

### Step 5: Publish Submission
# @name publishSubmission2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/publish2
Authorization: Bearer {{token}}

###

### Step 6: Unpublish Submission
# @name unpublishSubmission2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/unpublish2
Authorization: Bearer {{token}}

###


### Step 7: Download Submission Isolates
# @name downloadSubmissionIsolates2
POST {{folio}}/download/isolates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "isolates": ["205fe29a-1b07-4aeb-9da6-d089898087ec"]
}

##########################
### ELASTICSEARCH
##########################

# @name list_all_indices
GET http://localhost:9200/_cat/indices?v
Content-Type: application/json

###

# @name delete_indexed_samples
POST http://localhost:9200/agari-samples/_delete_by_query
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

###

# @name reindex_samples
POST {{folio}}/search/reindex?batch_size=50&offset=0
Authorization: Bearer {{token}}

###

# @name get_all_indexed_samples
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

###

# @name get_all_indexed_samples
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
    "sort": [
      {
        "host_age": {
          "order": "asc"
        }
      }
    ]
  }


###

# @name search_by_study_id
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "query": {
    "term": {
      "submission_id": "c5a7a0a5-5b67-4fb6-bebb-7b606927e904"
    }
  }
}

###

# @name search_by_submission_id_no_errors
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "submission_id.keyword": "<id>"
          }
        }
      ],
      "must_not": [
        {
          "exists": {
            "field": "seq_error"
          }
        },
        {
          "exists": {
            "field": "error"
          }
        }
      ]
    }
  }
}

###

# @name search_by_submission_id_with_seq_errors
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "submission_id.keyword": "<id>"
          }
        },
        {
          "exists": {
            "field": "seq_error"
          }
        }
      ]
    }
  }
}

###


# @name search_pagination
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "from": 0,
  "size": 50,
  "query": {
    "match_all": {}
  }
}

###


# @name tim_Queries1

POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "pathogen_id": "6d2494af-a5e5-4965-8494-ad618ba844db"
                    }
                },
                {
                    "term": {
                        "status": "published"
                    }
                }
            ]
        }
    },
    "from": 0,
    "size": 20,
    "track_total_hits": true
}

###

# @name tim_Queries2
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

# removing keyword works

{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "project_id": "5e2d9a3c-4fb3-4ec5-a8e3-98bb46a91e39"
                    }
                },
                {
                    "term": {
                        "pathogen_id": "bfebf404-e1cf-434d-8146-d68944118b9c"
                    }
                }
            ]
        }
    },
    "from": 0,
    "size": 25,
    "track_total_hits": true
}

###

# @name tim_Queries3
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

# removing keyword works

{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "project_id": "5e2d9a3c-4fb3-4ec5-a8e3-98bb46a91e39"
                    }
                },
                {
                    "term": {
                        "pathogen_id": "bfebf404-e1cf-434d-8146-d68944118b9c"
                    }
                },
                {
                    "bool": {
                        "should": [
                            {
                                "term": {
                                    "submission_id": "65dc13fb-9d7d-4839-ad34-684528a03b0e"
                                }
                            }
                        ],
                        "minimum_should_match": 1
                    }
                }
            ]
        }
    },
    "from": 0,
    "size": 0,
    "track_total_hits": true,
    "aggs": {
        "valid": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "bool": {
                                "must_not": [
                                    {
                                        "exists": {
                                            "field": "seq_error"
                                        }
                                    },
                                    {
                                        "exists": {
                                            "field": "error"
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        },
        "missingFasta": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "exists": {
                                "field": "seq_error"
                            }
                        }
                    ]
                }
            }
        }
    }
}

###

# @name tim_Queries4
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

# adding keyword to lineage_clade_name.keyword works


{
  "size": 0,
  "aggs": {
    "monthly_geo_lineage_pathogen_counts": {
      "composite": {
        "size": 50000,
        "sources": [
          {
            "sample_month": {
              "date_histogram": {
                "field": "sample_collection_date",
                "calendar_interval": "month",
                "format": "yyyy-MM",
                "missing_bucket": true
              }
            }
          },
          {
            "country": {
              "terms": {
                "field": "geo_loc_name_country",
                "missing_bucket": true
              }
            }
          },
          {
            "state_or_province": {
              "terms": {
                "field": "geo_loc_name_state_province_territory",
                "missing_bucket": true
              }
            }
          },
          {
            "lineage_name": {
              "terms": {
                "field": "lineage_clade_name",
                "missing_bucket": true
              }
            }
          },
          {
            "pathogen_id": {
              "terms": {
                "field": "pathogen_id",
                "missing_bucket": true
              }
            }
          }
        ]
      }
    }
  }
}

###

### Check if pathogen_id exists
# @name query-tests
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{"query":{"bool":{"filter":[{"term":{"project_id":"fb877b13-96ea-46e7-9762-30728b678521"}},{"term":{"pathogen_id":"bfebf404-e1cf-434d-8146-d68944118b9c"}}]}},"from":0,"size":25,"track_total_hits":true}