# @folio = http://localhost:8000
@folio = https://folio-staging.openup.org.za
# @folio = https://folio-ilifu.openup.org.za

# @keycloak = http://keycloak.local
@keycloak = https://keycloak-staging.openup.org.za
# @keycloak = https://keycloak-ilifu.openup.org.za

# @song = http://song.local
@song = https://song-staging.openup.org.za
# @song = https://song-ilifu.openup.org.za

# @score = http://score.local
@score = https://score-staging.openup.org.za
# @score = https://score-ilifu.openup.org.za

# @minio = http://minio.local
# @minio = http://localhost:9000


@realm = agari
@client_id = dms
@client_secret = VDyLEjGR3xDQvoQlrHq5AB6OwbW0Refc

@username = system.admin@agari.tech
# @username = owner@org1.ac.za
# @username = owner@org2.ac.za
# @username = org-admin@org1.ac.za
# @username = org-admin@org2.ac.za
# @username = test-user1@example.com
# @username = test-user2@example.com
# @username = test-user3@example.com
# @username = dirk@openup.org.za

@password = pass123

### 1. LOGIN to get access token
# @name login
POST {{keycloak}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}
&grant_type=password
&client_id={{client_id}}
&client_secret={{client_secret}}

###
@token = {{login.response.body.access_token}}


###

# @name whoami
GET {{folio}}/info/whoami
Authorization: Bearer {{token}}

###


##########################
### PROJECTS
##########################

# @name list_projects
GET {{folio}}/projects
Authorization: Bearer {{token}}

###

##########################
### SUBMISSIONS
##########################

# @name getProjectSubmissions
GET {{folio}}/projects/{{project_id}}/submissions
Authorization: Bearer {{token}}

###

# @name publish_analysis
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/publish
Authorization: Bearer {{token}}

###

# @name unpublish_analysis
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/unpublish
Authorization: Bearer {{token}}

###

##########################
### ELASTICSEARCH
##########################

# @name get_all_indexed_samples
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

###

######################
### DROPDOWN FILTERS
######################

@pathogen_id = 0a6050a3-03b3-4c67-978e-91f1b308d692

@project_id = 0a6050a3-03b3-4c67-978e-91f1b308d692
@field_id = geo_loc_name_country
# @field_id = specimen_collector_sample_id
# @field_id = biosample_accession
# @field_id = sequence_read_accession
# @field_id = sample_collected_by
# @field_id = sample_collection_date
# @field_id = purpose_of_sampling
# @field_id = geo_loc_name_state_province_territory
# @field_id = isolate_id
# @field_id = host_sex
# @field_id = fasta_header_name
# @field_id = fasta_file_name
# @field_id = purpose_of_sequencing
# @field_id = sequencing_date
# @field_id = sequencing_instrument
# @field_id = reference_genome_accession


# @name get_unique_values_for_field_in_project
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "size": 0,
  "query": {
    "term": {
      "projectId.keyword": "{{project_id}}"
    }
  },
  "aggs": {
    "unique_countries": {
      "terms": {
        "field": "{{field_id}}.keyword",
        "size": 1000
      }
    }
  }
}

###


# @name get_unique_values_for_field_in_pathogen
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

# Need to deploy app.py changes that add pathogenId to ES index first

{
  "size": 0,
  "query": {
    "term": {
      "pathogenId.keyword": "{{pathogen_id}}"
    }
  },
  "aggs": {
    "unique_countries": {
      "terms": {
        "field": "{{field_id}}.keyword",
        "size": 1000
      }
    }
  }
}

###

##########################
### SEARCH SAMPLES
##########################

@field_value = South Africa

# @name search_samples_by_field_value
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "query": {
    "term": {
      "{{field_id}}.keyword": "{{field_value}}"
    }
  }
}


###

# @name search_samples_by_multipole_field_values
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

# This is an OR search for samples matching any of the values

{
  "query": {
    "bool": {
      "should": [
        { "term": { "{{field_id}}.keyword": "South Africa" }},
        { "term": { "{{field_id}}.keyword": "Namibia" }}
      ],
      "minimum_should_match": 1
    }
  }
}

###

# @name search_samples_by_project_and_field_value
POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

# This is an AND search for samples matching both criteria

{
  "query": {
    "bool": {
      "must": [
        { "term": { "serotype.keyword": "Ogawa" }},
        { "term": { "{{field_id}}.keyword": "{{field_value}}" }}
      ]
    }
  }
}

##################################
### PAGINATION EXAMPLE
##################################

# @name search_pagination

POST {{folio}}/search/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "from": 0,
  "size": 50,
  "query": {
    "match_all": {}
  }
}
