@folio = http://localhost:8000
# @folio = https://folio-staging.openup.org.za
# @folio = https://folio-ilifu.openup.org.za

@keycloak = http://keycloak.local
# @keycloak = http://localhost:8080
# @keycloak = https://keycloak-staging.openup.org.za
# @keycloak = https://keycloak-ilifu.openup.org.za

# @minio = http://minio.local
# @minio = http://localhost:9000


@realm = agari
@client_id = dms
@client_secret = VDyLEjGR3xDQvoQlrHq5AB6OwbW0Refc

# @username = system.admin@agari.tech
# @username = owner@org1.ac.za
# @username = owner@org2.ac.za
# @username = org-admin@org1.ac.za
# @username = org-admin@org2.ac.za
# @username = test-user1@example.com
# @username = test-user2@example.com
# @username = test-user3@example.com
@username = dirk@openup.org.za

@password = pass123

### 1. LOGIN to get access token
# @name login
POST {{keycloak}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}
&grant_type=password
&client_id={{client_id}}
&client_secret={{client_secret}}

###
@token = {{login.response.body.access_token}}


##########################
### SUBMISSIONS2
##########################


@project_id = 884f2f0e-56a2-47b5-a311-5914215360d5
@submission_id = c15c0212-7beb-4f40-afea-5b8843cfd1cc

### Step 1: Get all submission
# @name getSubmission2
GET {{folio}}/projects/{{project_id}}/submissions2
Authorization: Bearer {{token}}
Content-Type: application/json

###


### Step 1: Create new submission
# @name createSubmission2
POST {{folio}}/projects/{{project_id}}/submissions2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "submission_name": "mpoxmon1"
}

###

### Step 2: Get the submission details
# @name getSubmission2
GET {{folio}}/projects/{{project_id}}/submissions2/{{submission_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

###


### Step 3a: Upload TSV file 
# @name uploadTSV2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/upload2
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="file"; filename="cholera_1_corrected.tsv"
Content-Type: text/tab-separated-values

< /home/dimee/Work/OpenUp/SANBI/agari-folio/test/data/tsv_files/cholera_1_corrected.tsv

--boundary123--

###

@file_id = 019bc3f8-7f50-497c-93a2-bb1997004f44

### Step 2c: Delete uploaded file
# @name deleteUploadedFile2
DELETE {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/files2/{{file_id}}
Authorization: Bearer {{token}}

###

### Step 3: Validate submission
# @name validateSubmission2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/validate2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "split_on_fasta_headers": false
}

###

### Step 3b: Validate submission
# @name ViewValidation
GET {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/validate2
Authorization: Bearer {{token}}

###


### Step 4: Finalise submission
# @name finalizeSubmission2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/finalise
Authorization: Bearer {{token}}

###

### Step 5: Publish Submission
# @name publishSubmission2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/publish2
Authorization: Bearer {{token}}

###

### Step 6: Unpublish Submission
# @name unpublishSubmission2
POST {{folio}}/projects/{{project_id}}/submissions/{{submission_id}}/unpublish2
Authorization: Bearer {{token}}

###


### Step 7: Download Submission Isolates
# @name downloadSubmissionIsolates2
POST {{folio}}/download/isolates
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "isolates": ["205fe29a-1b07-4aeb-9da6-d089898087ec"]
}