replicaCount: 1

image:
  repository: folio
  pullPolicy: "Never"
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 5001

# Folio application configuration
folio:
  auth:
    keycloak:
      host: "http://keycloak:8080"
      realm: "agari"
      issuer: "http://keycloak.local/realms/agari"
      clientId: "dms"
      clientSecret: "VDyLEjGR3xDQvoQlrHq5AB6OwbW0Refc"
  database:
    host: "folio-db"
    port: "5432"
    name: "folio"
    user: "admin"
    password: "folio-db-pass-123"

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: folio.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
