replicaCount: 1

image:
  repository: ghcr.io/openupsa/agari-folio
  pullPolicy: "IfNotPresent"
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 5001

# Folio application configuration
folio:
  auth:
    keycloak:
      host: "http://keycloak:8080"
      realm: "agari"
      issuer: "http://keycloak.local/realms/agari"
      clientId: "dms"
      clientSecret: "VDyLEjGR3xDQvoQlrHq5AB6OwbW0Refc"

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: folio.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
